- VMNET_BINDIR -> VM_BINDIR & moved top 'loctions' file
Changed files:
    VMware-workstation-vmnet.conf -> 1.3
    VMware-workstation.init -> 1.12

diff --git a/VMware-workstation.init b/VMware-workstation.init
--- a/VMware-workstation.init
+++ b/VMware-workstation.init
@@ -24,16 +24,19 @@ ping=vmware-ping
 smbd=vmware-smbd
 nmbd=vmware-nmbd
 
+# Source config files
 vmware_etc_dir=/etc/vmware
+vmware_locations="$vmware_etc_dir"/locations
 vmnet_cfg="$vmware_etc_dir"/vmnet.conf
-if [ -r "$vmnet_cfg" ]; then
-	. "$vmnet_cfg"
-else	
-	echo "Warning: Unable to find VMware Workstation's main database"
-	echo "($vmnet_cfg)."
-	echo	    
-	exit 1
-fi
+
+for f in $vmware_locations $vmnet_cfg; do
+	if [ -r $f ]; then
+		. $f
+	else	
+		echo "FATAL: Unable to read $f"
+		exit 1
+	fi
+done	
 
 # System wide functions
 . /etc/rc.d/init.d/functions
@@ -212,13 +215,13 @@ vmware_start_hostonly() {
 	# XXX ping takes 10 seconds to timeout if nobody answers
 	#     that slows boot too much so we do this bit in the
 	#     background.
-	if "$VMNET_BINDIR"/"$ping" -q "$ifIp"; then
+	if "$VM_BINDIR"/"$ping" -q "$ifIp"; then
 		echo 'Host-only networking disabled because '"$ifIp"
 		echo 'appears to be a real, physical, existing address.'
 		echo 'Please modify your host-only network configuration.'
 		exit 1
 	fi
-	cd "$VMNET_BINDIR" && "$VMNET_BINDIR"/"$netifup" \
+	cd "$VM_BINDIR" && "$VM_BINDIR"/"$netifup" \
 	-d /var/run/"$netifup"-"$vHostIf".pid /dev/vmnet"$vHubNr" "$vHostIf"
 	[ "$?" -eq 0 ] || exit 1
 	# Configure the virtual host ethernet interface and define the private IP
@@ -240,7 +243,7 @@ vmware_start_hostonly() {
 			# Start a DHCP server on a private IP network
 			# The daemon already logs its output in the system log, so we can safely
 			# trash it
-			cd "$VMNET_BINDIR" && "$VMNET_BINDIR"/"$dhcpd" \
+			cd "$VM_BINDIR" && "$VM_BINDIR"/"$dhcpd" \
 			-cf "$vmware_etc_dir"/"$vHostIf"/dhcpd/dhcpd.conf \
 			-lf "$vmware_etc_dir"/"$vHostIf"/dhcpd/dhcpd.leases \
 			-pf /var/run/"$dhcpd"-"$vHostIf".pid "$vHostIf" >/dev/null 2>&1 || exit 1
@@ -248,12 +251,12 @@ vmware_start_hostonly() {
 		if [ "$run_samba" = 'yes' ]; then
 			# Start a SMB name server on a private IP network
 			# Disable logging to avoid the uncontrolled creation of unmanaged files
-			cd "$VMNET_BINDIR" && "$VMNET_BINDIR"/"$nmbd" -D -l /dev/null \
+			cd "$VM_BINDIR" && "$VM_BINDIR"/"$nmbd" -D -l /dev/null \
 			-s "$vmware_etc_dir"/"$vHostIf"/smb/smb.conf \
 			-f /var/run/"$nmbd"-"$vHostIf".pid || exit 1
 			# Start a SMB share server on a private IP network
 			# Disable logging to avoid the uncontrolled creation of unmanaged files
-			cd "$VMNET_BINDIR" && "$VMNET_BINDIR"/"$smbd" -D -l /dev/null \
+			cd "$VM_BINDIR" && "$VM_BINDIR"/"$smbd" -D -l /dev/null \
 			-s "$vmware_etc_dir"/"$vHostIf"/smb/smb.conf \
 			-f /var/run/"$smbd"-"$vHostIf".pid || exit 1
 		fi
@@ -302,7 +305,7 @@ case "$1" in
 				# Connect a physical host ethernet interface to a virtual ethernet hub
 	        		msg_starting 'Bridged networking on /dev/vmnet'"$vHubNr"
 				busy
-				cd "$VMNET_BINDIR" && "$VMNET_BINDIR"/"$bridge" \
+				cd "$VM_BINDIR" && "$VM_BINDIR"/"$bridge" \
 				-d /var/run/"$bridge"-"$vHubNr".pid /dev/vmnet"$vHubNr" "$interface"
 				[ "$?" -eq 0 ] && ok || fail
 			elif [ -n "$hostaddr" -a -n "$netmask" ]; then
@@ -317,7 +320,7 @@ case "$1" in
 					# Start the NAT network user service
 					msg_starting 'NAT networking on /dev/vmnet'"$vHubNr"
 					busy
-					cd "$VMNET_BINDIR" && "$VMNET_BINDIR"/"$natd" \
+					cd "$VM_BINDIR" && "$VM_BINDIR"/"$natd" \
 					-d /var/run/"$natd"-"$vHubNr".pid \
 					-m /var/run/"$natd"-"$vHubNr".mac \
 					-c "$vmware_etc_dir"/vmnet"$vHubNr"/nat/nat.conf
