formatting, exitcode fixes
Changed files:
    VMware-workstation.init -> 1.13

diff --git a/VMware-workstation.init b/VMware-workstation.init
--- a/VMware-workstation.init
+++ b/VMware-workstation.init
@@ -66,26 +66,26 @@ make_tmp_dir() {
 		# Check the validity of the temporary directory. We do this in the loop
 		# because it can change over time
 		if [ ! -d "$tmp" ]; then
-    			echo 'Error: "'"$tmp"'" is not a directory.'
-    			echo
-    			exit 1
+			echo 'Error: "'"$tmp"'" is not a directory.'
+			echo
+			exit 1
 		fi
 		if [ ! -w "$tmp" -o ! -x "$tmp" ]; then
-    			echo 'Error: "'"$tmp"'" should be writable and executable.'
-    			echo
-    			exit 1
+			echo 'Error: "'"$tmp"'" should be writable and executable.'
+			echo
+			exit 1
 		fi
 		# Be secure
 		# -> Don't give write access to other users (so that they can not use this
 		# directory to launch a symlink attack)
 		if mkdir -m 0755 "$tmp"'/'"$prefix$serial" >/dev/null 2>&1; then
-    			loop='no'
+			loop='no'
 		else
-    			serial=`expr "$serial" + 1`
-    			if [ "`expr "$serial" % 200`" = '0' ]; then
-    				echo 'Warning: The "'"$tmp"'" directory may be under attack.'
-    				echo
-    			fi
+			serial=`expr "$serial" + 1`
+			if [ "`expr "$serial" % 200`" = '0' ]; then
+				echo 'Warning: The "'"$tmp"'" directory may be under attack.'
+				echo
+			fi
 		fi
 	done
 	eval "$dirname"'="$tmp"'"'"'/'"'"'"$prefix$serial"'
@@ -157,12 +157,12 @@ vmware_synchrone_kill() {
 	# Wait a bit to see if the dirty job has really been done
 	for second in 0 1 2 3 4 5 6 7 8 9 10; do
 		if [ ! -d /proc/"$pid" ]; then
-    			# Success
-    			return 0
+			# Success
+			return 0
 		fi
 		sleep 1
 	done
-        # Timeout
+	# Timeout
 	return 1
 }
 
@@ -222,7 +222,7 @@ vmware_start_hostonly() {
 		exit 1
 	fi
 	cd "$VM_BINDIR" && "$VM_BINDIR"/"$netifup" \
-	-d /var/run/"$netifup"-"$vHostIf".pid /dev/vmnet"$vHubNr" "$vHostIf"
+	  -d /var/run/"$netifup"-"$vHostIf".pid /dev/vmnet"$vHubNr" "$vHostIf"
 	[ "$?" -eq 0 ] || exit 1
 	# Configure the virtual host ethernet interface and define the private IP
 	# network
@@ -234,32 +234,32 @@ vmware_start_hostonly() {
 	#   just discard messages from route, but instead check if the route got
 	#   installed before manually adding one.
 	ifNet=`ipv4_subnet "$ifIp" "$ifMask"`
-		if ifconfig "$vHostIf" inet "$ifIp" netmask "$ifMask" \
-        	broadcast "`ipv4_broadcast "$ifIp" "$ifMask"`" up \
-    		&& noRoutePresent "$ifNet" "$vHostIf"; then
-    			route add -net "$ifNet" netmask "$ifMask" "$vHostIf"
-		fi
-		if [ "$run_dhcpd" = 'yes' ]; then
-			# Start a DHCP server on a private IP network
-			# The daemon already logs its output in the system log, so we can safely
-			# trash it
-			cd "$VM_BINDIR" && "$VM_BINDIR"/"$dhcpd" \
-			-cf "$vmware_etc_dir"/"$vHostIf"/dhcpd/dhcpd.conf \
-			-lf "$vmware_etc_dir"/"$vHostIf"/dhcpd/dhcpd.leases \
-			-pf /var/run/"$dhcpd"-"$vHostIf".pid "$vHostIf" >/dev/null 2>&1 || exit 1
-		fi
-		if [ "$run_samba" = 'yes' ]; then
-			# Start a SMB name server on a private IP network
-			# Disable logging to avoid the uncontrolled creation of unmanaged files
-			cd "$VM_BINDIR" && "$VM_BINDIR"/"$nmbd" -D -l /dev/null \
-			-s "$vmware_etc_dir"/"$vHostIf"/smb/smb.conf \
-			-f /var/run/"$nmbd"-"$vHostIf".pid || exit 1
-			# Start a SMB share server on a private IP network
-			# Disable logging to avoid the uncontrolled creation of unmanaged files
-			cd "$VM_BINDIR" && "$VM_BINDIR"/"$smbd" -D -l /dev/null \
-			-s "$vmware_etc_dir"/"$vHostIf"/smb/smb.conf \
-			-f /var/run/"$smbd"-"$vHostIf".pid || exit 1
-		fi
+	if ifconfig "$vHostIf" inet "$ifIp" netmask "$ifMask" \
+	  broadcast "`ipv4_broadcast "$ifIp" "$ifMask"`" up \
+	  && noRoutePresent "$ifNet" "$vHostIf"; then
+		route add -net "$ifNet" netmask "$ifMask" "$vHostIf"
+	fi
+	if [ "$run_dhcpd" = 'yes' ]; then
+		# Start a DHCP server on a private IP network
+		# The daemon already logs its output in the system log, so we can safely
+		# trash it
+		cd "$VM_BINDIR" && "$VM_BINDIR"/"$dhcpd" \
+		  -cf "$vmware_etc_dir"/"$vHostIf"/dhcpd/dhcpd.conf \
+		  -lf "$vmware_etc_dir"/"$vHostIf"/dhcpd/dhcpd.leases \
+		  -pf /var/run/"$dhcpd"-"$vHostIf".pid "$vHostIf" >/dev/null 2>&1 || exit 1
+	fi
+	if [ "$run_samba" = 'yes' ]; then
+		# Start a SMB name server on a private IP network
+		# Disable logging to avoid the uncontrolled creation of unmanaged files
+		cd "$VM_BINDIR" && "$VM_BINDIR"/"$nmbd" -D -l /dev/null \
+		  -s "$vmware_etc_dir"/"$vHostIf"/smb/smb.conf \
+		  -f /var/run/"$nmbd"-"$vHostIf".pid || exit 1
+		# Start a SMB share server on a private IP network
+		# Disable logging to avoid the uncontrolled creation of unmanaged files
+		cd "$VM_BINDIR" && "$VM_BINDIR"/"$smbd" -D -l /dev/null \
+		  -s "$vmware_etc_dir"/"$vHostIf"/smb/smb.conf \
+		  -f /var/run/"$smbd"-"$vHostIf".pid || exit 1
+	fi
 }
 
 # Stop the host-only network user service
@@ -271,7 +271,7 @@ vmware_stop_hostonly() {
 
 	# Terminate the private network
 	ifNet=`ipv4_subnet "$ifIp" "$ifMask"`
-        noRoutePresent "$ifNet" "$vHostIf" || route del -net "$ifNet" netmask "$ifMask" || exit 1
+	noRoutePresent "$ifNet" "$vHostIf" || route del -net "$ifNet" netmask "$ifMask" || exit 1
 	# To test if the interface exists, we can not just look at the exitcode
 	# because old versions of ifconfig don't exit with 1 when invoked with a
 	# non-existing interface
@@ -286,11 +286,10 @@ case "$1" in
   start)
 	if [ -f /var/lock/subsys/"$subsys" ]; then
 		msg_already_running "VMware Workstation networking"
-		exit 1
 	fi	
-    	# Try to load parport_pc. Failure is allowed as it does not exist
-    	# on kernels 2.0
-    	/sbin/modprobe parport_pc >/dev/null 2>&1
+	# Try to load parport_pc. Failure is allowed as it does not exist
+	# on kernels 2.0
+	/sbin/modprobe parport_pc >/dev/null 2>&1
 	if [ "$VM_NETWORKING" = 'yes' ]; then
 		msg_starting 'Virtual ethernet'
 		busy
@@ -298,67 +297,64 @@ case "$1" in
 		[ "$?" -eq 0 ] && ok || fail
 		vHubNr=0
 		while [ $vHubNr -lt 8 ]; do
-	    		eval 'interface="$VNET_'"$vHubNr"'_INTERFACE"'
-	    		eval 'hostaddr="$VNET_'"$vHubNr"'_HOSTONLY_HOSTADDR"'
-	    		eval 'netmask="$VNET_'"$vHubNr"'_HOSTONLY_NETMASK"'
+			eval 'interface="$VNET_'"$vHubNr"'_INTERFACE"'
+			eval 'hostaddr="$VNET_'"$vHubNr"'_HOSTONLY_HOSTADDR"'
+			eval 'netmask="$VNET_'"$vHubNr"'_HOSTONLY_NETMASK"'
 			if [ -n "$interface" ]; then
 				# Connect a physical host ethernet interface to a virtual ethernet hub
-	        		msg_starting 'Bridged networking on /dev/vmnet'"$vHubNr"
+				msg_starting 'Bridged networking on /dev/vmnet'"$vHubNr"
 				busy
 				cd "$VM_BINDIR" && "$VM_BINDIR"/"$bridge" \
-				-d /var/run/"$bridge"-"$vHubNr".pid /dev/vmnet"$vHubNr" "$interface"
+				  -d /var/run/"$bridge"-"$vHubNr".pid /dev/vmnet"$vHubNr" "$interface"
 				[ "$?" -eq 0 ] && ok || fail
 			elif [ -n "$hostaddr" -a -n "$netmask" ]; then
 				eval 'samba="$VNET_'"$vHubNr"'_SAMBA"'
-	        		msg_starting 'Host-only networking on /dev/vmnet'"$vHubNr"
+				msg_starting 'Host-only networking on /dev/vmnet'"$vHubNr"
 				busy
-	        		daemon vmware_start_hostonly "$vHubNr" 'vmnet'"$vHubNr" "$hostaddr" \
-				"$netmask" 'yes' "$samba"
+				daemon vmware_start_hostonly "$vHubNr" 'vmnet'"$vHubNr" "$hostaddr" \
+				  "$netmask" 'yes' "$samba"
 				[ "$?" -eq 0 ] && ok || fail
 				eval 'nat="$VNET_'"$vHubNr"'_NAT"'
-                		if [ "$nat" = 'yes' ]; then
+				if [ "$nat" = 'yes' ]; then
 					# Start the NAT network user service
 					msg_starting 'NAT networking on /dev/vmnet'"$vHubNr"
 					busy
 					cd "$VM_BINDIR" && "$VM_BINDIR"/"$natd" \
-					-d /var/run/"$natd"-"$vHubNr".pid \
-					-m /var/run/"$natd"-"$vHubNr".mac \
-					-c "$vmware_etc_dir"/vmnet"$vHubNr"/nat/nat.conf
+					  -d /var/run/"$natd"-"$vHubNr".pid \
+					  -m /var/run/"$natd"-"$vHubNr".mac \
+					  -c "$vmware_etc_dir"/vmnet"$vHubNr"/nat/nat.conf
 					[ "$?" -eq 0 ] && ok || fail
-                		fi
+				fi
 			fi
-	    		vHubNr=$(($vHubNr + 1))
+			vHubNr=$(($vHubNr + 1))
 		done
-
 	fi
 	touch /var/lock/subsys/"$subsys"
 	;;
 
   stop)
-        if [ "`countVMs`" -gt 0 ]; then
-    		echo 'At least one instance of VMware Workstation is still running.'
+	if [ "`countVMs`" -gt 0 ]; then
+		echo 'At least one instance of VMware Workstation is still running.'
 		echo 'Please stop all running instances of VMware Workstation first.'
 		echo
-    		exit 1
 	fi
 	if [ ! -f /var/lock/subsys/"$subsys" ]; then
 		msg_not_running "VMware Workstation networking"
-		exit 1
 	fi	
-    	# Try to unload parport_pc. Failure is allowed as it does not exist
-    	# on kernels 2.0, and some other process could be using it.
-    	/sbin/modprobe -r parport_pc >/dev/null 2>&1
+	# Try to unload parport_pc. Failure is allowed as it does not exist
+	# on kernels 2.0, and some other process could be using it.
+	/sbin/modprobe -r parport_pc >/dev/null 2>&1
 	if [ "$VM_NETWORKING" = "yes" ]; then
 		# NB: must kill off processes using vmnet before
 		#     unloading module
 		vHubNr=0
 		while [ $vHubNr -lt 8 ]; do
-	    		eval 'interface="$VNET_'"$vHubNr"'_INTERFACE"'
-	    		eval 'hostaddr="$VNET_'"$vHubNr"'_HOSTONLY_HOSTADDR"'
-	    		eval 'netmask="$VNET_'"$vHubNr"'_HOSTONLY_NETMASK"'
+			eval 'interface="$VNET_'"$vHubNr"'_INTERFACE"'
+			eval 'hostaddr="$VNET_'"$vHubNr"'_HOSTONLY_HOSTADDR"'
+			eval 'netmask="$VNET_'"$vHubNr"'_HOSTONLY_NETMASK"'
 			if [ -n "$interface" ]; then
 				# Disconnect a physical host ethernet interface from a virtual ethernet hub
-	        		msg_stopping "Bridged networking on /dev/vmnet$vHubNr"
+				msg_stopping "Bridged networking on /dev/vmnet$vHubNr"
 				busy
 				vmware_stop_pidfile /var/run/"$bridge"-"$vHubNr".pid
 				[ "$?" -eq 0 ] && ok || fail
@@ -369,64 +365,64 @@ case "$1" in
 				vmware_stop_pidfile /var/run/"$dhcpd"-"vmnet$vHubNr".pid
 				[ "$?" -eq 0 ] && ok || fail
 				eval 'samba="$VNET_'"$vHubNr"'_SAMBA"'
-                		if [ "$samba" = "yes" ]; then
+				if [ "$samba" = "yes" ]; then
 					# Stop a SMB share server on a private IP network
-	            			msg_stopping 'SMB share server on /dev/vmnet'"$vHubNr"
+					msg_stopping 'SMB share server on /dev/vmnet'"$vHubNr"
 					busy
 					vmware_stop_pidfile /var/run/"$smbd"-'vmnet'"$vHubNr".pid
 					[ "$?" -eq 0 ] && ok || fail
 					# Stop a SMB name server on a private IP network
-	            			msg_stopping 'SMB name server on /dev/vmnet'"$vHubNr"
+					msg_stopping 'SMB name server on /dev/vmnet'"$vHubNr"
 					busy
 					vmware_stop_pidfile /var/run/"$nmbd"-'vmnet'"$vHubNr".pid
 					[ "$?" -eq 0 ] && ok || fail
 				fi
 				eval 'nat="$VNET_'"$vHubNr"'_NAT"'
-                			if [ "$nat" = "yes" ]; then
-						# Stop the NAT network user service
-                    				msg_stopping 'NAT networking on /dev/vmnet'"$vHubNr"
-						busy
-						vmware_stop_pidfile /var/run/"$natd"-"$vHubNr".pid
-						[ "$?" -eq 0 ] && ok || fail
-					fi
-                			msg_stopping 'Host-only networking on /dev/vmnet'"$vHubNr"
+				if [ "$nat" = "yes" ]; then
+					# Stop the NAT network user service
+					msg_stopping 'NAT networking on /dev/vmnet'"$vHubNr"
 					busy
-                			vmware_stop_hostonly 'vmnet'"$vHubNr" "$hostaddr" "$netmask"
+					vmware_stop_pidfile /var/run/"$natd"-"$vHubNr".pid
 					[ "$?" -eq 0 ] && ok || fail
+				fi
+				msg_stopping 'Host-only networking on /dev/vmnet'"$vHubNr"
+				busy
+				vmware_stop_hostonly 'vmnet'"$vHubNr" "$hostaddr" "$netmask"
+				[ "$?" -eq 0 ] && ok || fail
 
 			fi
-	    		vHubNr=$(($vHubNr + 1))
+			vHubNr=$(($vHubNr + 1))
 		done
 		msg_stopping 'Virtual ethernet'
 		busy
 		if /sbin/lsmod | grep -q ^"$vnet"; then
-    			/sbin/rmmod "$vnet"
+			/sbin/rmmod "$vnet"
 		fi
 		[ "$?" -eq "0" ] && ok || fail
-        fi
+	fi
 	rm -f /var/lock/subsys/"$subsys"
 	;;
   status)
-        if [ "`countVMs`" -gt 0 ]; then
-        	echo 'At least one instance of VMware Workstation is still running.'
-        	echo
+	if [ "`countVMs`" -gt 0 ]; then
+		echo 'At least one instance of VMware Workstation is still running.'
+		echo
 	fi
 	if [ "$VM_NETWORKING" = "yes" ]; then
-        	status "$bridge"
-        	status "$dhcpd"
-        	status "$netifup"
-        fi
+		status "$bridge"
+		status "$dhcpd"
+		status "$netifup"
+	fi
 	if [ "$VM_NETWORKING" = "yes" ]; then
-        	echo -n "Module $vnet "
-        	/sbin/modprobe "$vnet" >/dev/null 2>&1 && echo installed || echo "not installed"
-        fi
+		echo -n "Module $vnet "
+		/sbin/modprobe "$vnet" >/dev/null 2>&1 && echo installed || echo "not installed"
+	fi
 	;;
   restart)
 	"$0" stop && "$0" start
 	;;
   *)
 	echo "Usage: `basename "$0"` {start|stop|status|restart}"
-	exit 1
+	exit 3
 esac
 
 exit 0
